apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  name: tls.sem-ugr-k8s.arsahosting.com
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1VENDQTJ5Z0F3SUJBZ0lTQnE2STBzNHNoY1h3YlZIUjZpMm42MUUyTUFvR0NDcUdTTTQ5QkFNRE1ESXgKQ3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MU1aWFFuY3lCRmJtTnllWEIwTVFzd0NRWURWUVFERXdKRgpOVEFlRncweU5UQTFNRFV3TWpReE1EaGFGdzB5TlRBNE1ETXdNalF4TURkYU1DZ3hKakFrQmdOVkJBTU1IU291CmMyVnRMWFZuY2kxck9ITXVZWEp6WVdodmMzUnBibWN1WTI5dE1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMEQKQVFjRFFnQUVzV3pZRVN2d1ZqbnpqdFo4bTcrbTFZcnZONjg5c0FpeU1udkt0bEIwOWJIY0cwMXhNTElDWDRVZApvRzgzSnFpZTdVWFBSZDRtZFZyY2luZHpteHYzMmFPQ0Ftb3dnZ0ptTUE0R0ExVWREd0VCL3dRRUF3SUhnREFkCkJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlYKSFE0RUZnUVU3eFhzais1WG5wb1NadlVQUm1uRmZKeGRQbFV3SHdZRFZSMGpCQmd3Rm9BVW55dGZ6endoVDUwRQp0KzByTE1UR2NJdlMxdzB3VlFZSUt3WUJCUVVIQVFFRVNUQkhNQ0VHQ0NzR0FRVUZCekFCaGhWb2RIUndPaTh2ClpUVXVieTVzWlc1amNpNXZjbWN3SWdZSUt3WUJCUVVITUFLR0ZtaDBkSEE2THk5bE5TNXBMbXhsYm1OeUxtOXkKWnk4d1JRWURWUjBSQkQ0d1BJSWRLaTV6WlcwdGRXZHlMV3M0Y3k1aGNuTmhhRzl6ZEdsdVp5NWpiMjJDRzNObApiUzExWjNJdGF6aHpMbUZ5YzJGb2IzTjBhVzVuTG1OdmJUQVRCZ05WSFNBRUREQUtNQWdHQm1lQkRBRUNBVEF0CkJnTlZIUjhFSmpBa01DS2dJS0FlaGh4b2RIUndPaTh2WlRVdVl5NXNaVzVqY2k1dmNtY3ZOVFV1WTNKc01JSUIKQXdZS0t3WUJCQUhXZVFJRUFnU0I5QVNCOFFEdkFIVUFwRUxGQmtsZ1lWU1BEOVRxblB0NkxTWkZUWWVwZnkvZgpSVm4ySjA4NmhGUUFBQUdXbm9jaWtRQUFCQU1BUmpCRUFpQklPZ21PWldZeS9wUzdtWjAvaEdPMEpDMThvdEpyCjc5RmUxOWRLajZtVERBSWdhblBRZ2JZV3B4NGl6ZzdNaExUNDF5Zm54TzRTZDA3VnRJY01MeW9Gam5FQWRnQWEKQlA5SjBGUWRRSy8yb01PLzhkakVaeTlPN080alFHaVlheGRBTHR5SmZRQUFBWmFlaHlVbkFBQUVBd0JITUVVQwpJUUM3VGw0VUdIZHh3WE1oZ0dJRUZ6NFhqWkZUR2toNldGcXk1UmVrcnBmZXd3SWdiaG1zd1lNYXRIUTM1amFqCmxGY1BiemJZUzVBb2VONDQ3a2VTTmZSb0JXWXdDZ1lJS29aSXpqMEVBd01EWndBd1pBSXdJbWM1TjAvTlFPWFgKNEtuRDI2SDUzbjhaNi9Wbm85NmxYeUxRNzc4b1BDOGg3b1pXWmNYQittcWZtblpnbTMrL0FqQVpHd3hYU2l3UgpRSW9ySy94WUhsclo3T285Q3NQR3dxYWYwSHhNYmxJRTBuS1NPNDVwUEYxMUt6aHJJVkJuQXowPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZzBPNjkzWlpMMmprUmtpQVoKUEtjWnVhWGZSL01IYjR6OGszUVkrU2dLenRPaFJBTkNBQVN4Yk5nUksvQldPZk9PMW55YnY2YlZpdTgzcnoydwpDTEl5ZThxMlVIVDFzZHdiVFhFd3NnSmZoUjJnYnpjbXFKN3RSYzlGM2laMVd0eUtkM09iRy9mWgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.sem-ugr-k8s.arsahosting.com`)
      priority: 10
      services:
        - name: argocd-server
          port: http
    - kind: Rule
      match: Host(`argocd.sem-ugr-k8s.arsahosting.com`) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: http
          scheme: h2c
  tls:
    secretName: tls.sem-ugr-k8s.arsahosting.com
